### ISSUE TITLE
Update coomand using update source code 0.21.1

### ISSUE THREAD

**Issue by bovirus** [mlocati/gettext-iconv-windows#14]
@mlocati 

Could you please update your msgxxx exe collection tools using new source code 021.1 (09.10.2022)

https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.1.tar.gz

Thanks.

**Comment by bovirus** [comment]
@mlocati 

No news?

**Comment by mlocati** [comment]
@bovirus I tried some time ago to build gettext 0.21.1, but after a few hours I gave up: see https://github.com/mlocati/test/tree/main/.github/workflows

**Comment by bovirus** [comment]
@mlocati 

Thanks. When will be available a new package of your tools?
I hope always with "shared" and "static" version.

It seems that also the latest has a bug regarding when you want to use not automatic wordwarp at 77 characters and set a long line lenght (ex. 200).
It seems that didn't work.

**Comment by mlocati** [comment]
> When will be available a new package of your tools?

They will be available when I'll fine some spare time.

> It seems that also the latest has a bug

And this project `mlocati/gettext-iconv-windows` is not about gettext bugs: is just for creating the gettext executables.

You should report bugs at https://savannah.gnu.org/bugs/?group=gettext

**Comment by insinfo** [comment]
It would be great if there was a newer version of iconv, I searched all over the internet and couldn't find an updated version.

```
root@appserver:/tmp# iconv --version
iconv (Debian GLIBC 2.36-9) 2.36
Copyright (C) 2022 Free Software Foundation, Inc.
Este é um software livre; leia os fontes para condições de cópia. NÃO HÁ
QUALQUER GARANTIA; nem para COMERCIALIZAÇÃO ou ADEQUAÇÃO A QUALQUER
PROPÓSITO EME PARTICULAR.
Escrito por Ulrich Drepper.
```
