### ISSUE TITLE
please consider to package the binaries as zip files for easier extraction

### ISSUE THREAD

**Issue by chrisbra** [mlocati/gettext-iconv-windows#4]
Hi,
please consider to make the 32bit and 64bit binaries available as simple zip files such that they can be automatically downloaded and extracted. 

Thanks.

**Comment by mlocati** [comment]
Sorry for the very long delay: I wanted to fix this while building the most recent gettext version, but it required a lot of work.
In the most recent release I added a "zip" version too.

**Comment by chrisbra** [comment]
thanks!
