### ISSUE TITLE
Uninstaller does not remove registry value

### ISSUE THREAD

**Issue by chrisbra** [mlocati/gettext-iconv-windows#5]
The installation updates the registry HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\Path and adds the gettext location to it. However, even after uninstalling the old gettext path still remains there.

After having played around with your binaries and having them installed in different locations, my path variable showed up several old gettext installation.

**Comment by mlocati** [comment]
Sorry for the very long delay: I wanted to fix this while building the most recent gettext version, but it required a lot of work.
This issue has been fixed in the latest release (I had to patch the modpath.iss file).

**Comment by chrisbra** [comment]
thanks!
