### ISSUE TITLE
New Release does not contain libwinpthread.dll

### ISSUE THREAD

**Issue by chrisbra** [mlocati/gettext-iconv-windows#6]
Hi,
I am using your gettext-iconv-windows release for building the vim/vim-win32-installer releases for Windows. Until now, I have been using the old release v0.19.6-v1.14 and this works without problems. I now wanted to switch to the new provided release v0.19.8.1-iconv1.14-shared. However, the new release does not contain libwinpthread-1.dll anymore and we need this when building the 64bit version for proper gettext support. So can you please also build the libwinpthread-1.dll?

Thanks.

**Comment by mlocati** [comment]
Hi!

What's the gettext executable that needs it? I'm not 100% sure, but it seems to me that all the shipped exes in both the shared and static versions don't need libwinpthread-1.dll...

**Comment by chrisbra** [comment]
Hm, so I don't need that dll for the latest gettext release from your repository? I'll have to check and manually build those images and see if it works without libwinpthread-1.dll

**Comment by mlocati** [comment]
Starting from v0.19.8.1-v1.14, I changed the build environment (now I use MXE): that may be the reason why we don't need libwinpthread-1.dll anymore...

**Comment by chrisbra** [comment]
okay tried it. Unfortunately it does not seem to work: See here https://github.com/chrisbra/vim-win32-installer/releases/tag/v8.0.0314d

**Comment by mlocati** [comment]
What should I look at in that page?

**Comment by chrisbra** [comment]
okay, that was a little bit unclear from my side. so let me just explain in more detail:

The github repository vim/vim-win32-installer is used to automatically build binary gvims for the Windows plattform by using appveyor. So it basically runs every night, checks if there are new patches from the upstream vim/vim repository and builds, tests and deploys them back to github so users can easily download an updated Vim version on Windows. Until now it uses your old release [v.019.6-1.14 release](https://github.com/vim/vim-win32-installer/blob/master/appveyor.bat#L61-L63) (see also [here](https://github.com/vim/vim-win32-installer/blob/master/appveyor.bat#L126-L127)  and [here](https://github.com/vim/vim-win32-installer/blob/master/appveyor.bat#L220-L221) to build gvim allowing it for using localized messages.

Now I used my private fork to see how it would work with your latest release v0.19.8.1-v1.14 So I adapted the build script for your new release [commit](https://github.com/chrisbra/vim-win32-installer/commit/e205e753541beaab211f5f17dacbd4ea8924333b) and let it build a new version on [appveyor (build log)](https://ci.appveyor.com/project/chrisbra/vim-win32-installer-33v6e/build/job/77u0eurch6d9f4rb) and this was then uploaded to https://github.com/chrisbra/vim-win32-installer/releases/tag/v8.0.0314d

I then downloaded that version and tried that gvim version locally. And unfortunately, localizing the messages did not work.

I am at loss here, because I do not know all the details about how gettext works, so I really do not know, whether I need some change to Vim or not. (But even copying the libwinpthread-1.dll from an older build does not work, by that I mean, I always only get english messages, although I have setup gvim for using localized messages.).

**Comment by mlocati** [comment]
> https://github.com/chrisbra/vim-win32-installer/releases/tag/v8.0.0314d

This link doesn't work, and I can't see any executable in at https://github.com/chrisbra/vim-win32-installer/releases
Where can I find working (eg with v.019.6-1.14) and not working (eg with v0.19.8.1-v1.1) executables?

**Comment by chrisbra** [comment]
darn, I accidentally deleted that tag. Try those attached here: [gvim_8.0.0314d_x86.zip](https://github.com/mlocati/gettext-iconv-windows/files/760902/gvim_8.0.0314d_x86.zip)
[gvim_8.0.0314d_x64.zip](https://github.com/mlocati/gettext-iconv-windows/files/760923/gvim_8.0.0314d_x64.zip)

The gvim_8.0.0314d_*.zip releases are using the v0.19.8.1-v1.1 release (one for 32bit and one for 64bit)
Working releases can be found [here](http://github.com/vim/vim-win32-installer/releases)

**Comment by mlocati** [comment]
I tried both 32 and 64 bit versions, and I see them localized:

![image](https://cloud.githubusercontent.com/assets/928116/22746707/0ca665aa-ee25-11e6-9648-63c0ef4ce995.png)

**Comment by chrisbra** [comment]
Hm, thanks for trying out. Then it must be a local problem here. I guess I have to test this some more. 
Did you use a vimrc for configuration or simply started it without any configuration? can you show the output of `:lang`? Thanks.

**Comment by mlocati** [comment]
I started it from command prompt (after clearing the `PATH` variable just to be sure that your archive contains all the required DLLs).

```
J:\Download\gvim_8.0.0314d_x64\vim\vim80>set PATH=
J:\Download\gvim_8.0.0314d_x64\vim\vim80>gvim.exe
J:\Download\gvim_8.0.0314d_x64\vim\vim80>
```

BTW, even double-clicking the `gvim.exe` icon works.

The output of `:lang` is:
```
Lingua in uso: "LC_COLLATE=Italian_Italy.1252;LC_CTYPE=C;LC_MONETARY=Italian_Ita
ly.1252;LC_NUMERIC=C;LC_TIME=Italian_Italy.1252"
```

(where `Lingua in uso` means `Language used`)

**Comment by chrisbra** [comment]
Ah thanks. I did in fact have a `:lang C` inside my .vimrc (which did not work in my old version, because of a bug, that has been fixed in the meantime.). So it works for the 64bit version. However, it seems like my 32bit version doesn't, so can you please check again that https://github.com/mlocati/gettext-iconv-windows/files/760902/gvim_8.0.0314d_x86.zip actually works?

**Comment by chrisbra** [comment]
I did the same as you, started cmd.exe, changed to that directory, made the path empty and started gvim.exe

**Comment by k-takata** [comment]
I found that only 32-bit libintl-8.dll depends on libgcc_s_sjlj-1.dll. I don't think this is expected.

I also confirmed that both 32- and 64-bit libintl-8.dll and libiconv-2.dll don't depend on libwinpthread-1.dll.

**Comment by mlocati** [comment]
@chrisbra Could you try to add the `libgcc_s_sjlj-1.dll` library (included in the shared 32 bit) to the folder containing `gvim.exe` and see if this fixes your problems?

PS: you should really use [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) to solve problems like this: launch it, set the "Process Name" filter to "gvim.exe", and hit "Add": you'll see what's happening, including which DLL libraries gvim.exe (tries to) load.

![image](https://cloud.githubusercontent.com/assets/928116/22773337/e96bce68-eea1-11e6-8f11-cec65dbfe250.png)

**Comment by chrisbra** [comment]
> libgcc_s_sjlj-1.dll 

thanks that was it.

Thanks also for the tip with process monitor. I have used it in the past, but didn't remember to use it. I'll close it then.
