### ISSUE TITLE
Dependency on libgcc_s_sjlj-1.dll for 32bit versions.

### ISSUE THREAD

**Issue by chrisbra** [mlocati/gettext-iconv-windows#7]
As has been pointed out in #6 it seems like that libintl-8.dll has a new dependency on libgcc_s_sjlj-1.dll Is that correct? I am wondering, because if that is correct also for future releases, we have to fix vim and the vim-installer build to included that dll as well. So before I put effort to change that on our side, I just want to make sure that this dependency is intended and will stay so in the future.

References vim/vim-win32-installer#20

**Comment by mlocati** [comment]
I don't plan to switch the build environment in the foreseeable future: mxe is really helpful.

BTW I don't have control neither on the gettext source code nor on the mxe build environment...

**Comment by chrisbra** [comment]
okay, I am closing this then.
